name: PayForCommand
version: 1.17
api-version: 1.13
main: me.F_o_F_1092.PayForCommand.Main
author: F_o_F_1092
commands:
  PayForCommand:
    description: none
    usage: /PayForCommand
    aliases: [pfc]